name: Selenium Framework Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Automation Tests
        run: mvn test
